about/urls.py
from django.urls import path
from about import views

app_name = "about"
urlpatterns = [
    path("", views.dolc),
    path("dolc/", views.dolc, name="dolc"),
    path("team/", views.team, name="team"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('about/', include("about.urls", namespace="about")),
    path('events/', include("events.urls",  namespace="events")),
    path('participants/', include("participants.urls",  namespace="parti")),
    path('registration/', include("registration.urls",  namespace="regis")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from events import views

app_name = "events"
urlpatterns = [
    path("", views.index, name="events"),
    path("events-data/", views.get_event),
]

home/urls.py
from django.urls import path
from home import views

app_name = "home"
urlpatterns = [
    path("", views.index, name="home"),
    path("home/", views.index, name="home"),
    path("supporter/<str:type>-data/", views.get_supporter),
]

participants/urls.py
from django.urls import path
from participants import views

app_name = "parti"
urlpatterns = [
    path("", views.parti, name="parti"),
    path("participants-data/", views.participants),
    path("agency-data/", views.agency),
]

registration/urls.py
from django.urls import path
from registration import views

app_name = "regis";
urlpatterns = [
    path("", views.regis, name="regis"),
    path("etc/ielts/", views.ielts, name="ielts"),
    path("talkshow/<str:topic>/", views.event),
    path("workshop/<str:topic>/", views.event),
    path("<str:type>-data/", views.get_data),
]

about/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models

# Create your models here.
class Event(models.Model):
    photo = models.ImageField(upload_to="imgs/events/", blank=True, null=True)
    title = models.CharField(max_length=100)
    description = models.TextField(max_length=2000)
    place = models.CharField(max_length=100, null=True)
    date = models.TextField(max_length=100, null=True)
    def __str__(self):
        return self.title

home/models.py
from django.db import models

# Create your models here.
class SupporterSize(models.Model):
    name = models.CharField(max_length = 50)
    size = models.CharField(max_length = 50)
    def __str__(self):
        return self.name

class SupporterType(models.Model):
    name = models.CharField(max_length = 50)
    def __str__(self):
        return self.name

class Supporter(models.Model):
    img = models.ImageField(upload_to = "imgs/supporters/", null=True)
    name = models.CharField(max_length = 50)
    type = models.ForeignKey(SupporterType, on_delete=models.SET_NULL, null=True)
    size = models.ForeignKey(SupporterSize, on_delete=models.SET_NULL, null=True)
    def __str__(self):
        return self.name

participants/models.py
from django.db import models

# Create your models here.
class Participant(models.Model):
    name = models.CharField(max_length=50)
    comment = models.TextField(max_length=300)
    photo = models.ImageField(upload_to="imgs/participants/", blank=True, null=True)
    def __str__(self):
        return self.name

class Agency(models.Model):
    name = models.CharField(max_length=50)
    desc = models.TextField(max_length=300)
    photo = models.ImageField(upload_to="imgs/agencies/", blank=True, null=True)
    def __str__(self):
        return self.name

about/views.py
from django.shortcuts import render

# Create your views here.
def dolc(request):
    data = {}
    return render(request, "main-pages/about-dolc.html")

def team(request):
    data = {}
    return render(request, "main-pages/about-team.html")

events/views.py
from django.shortcuts import render
from django.http import JsonResponse
from events import models

# Create your views here.
def index(request):
    data = {
        "events": models.Event.objects.all(),
    }
    return render(request, "main-pages/events.html", data)

def get_event(request):
    data = {
        "success": False,
    }
    if request.method == "GET":
        events = models.Event.objects.all();
        if events.first() != None:
            data["events"] = []
            for event in events:
                data["events"].append({
                    "photo": event.photo.url,
                    "title": event.title,
                    "desc": event.description,
                    "place": event.place,
                    "date": event.date 
                })
            data["success"] = True
    return JsonResponse(data)

home/views.py
from django.shortcuts import render
from django.http import JsonResponse
from home import models
from participants.models import Participant
# Create your views here.
def index(request):
    data = {
        "participants": Participant.objects.all(),
    }
    return render(request, "main-pages/home.html", data)

def get_supporter(request, type):
    data = {
        "success": False,
    }
    if request.method == "GET" and (type.lower() in ["sponsor", "media"]):
        supporters = models.Supporter.objects.filter(type__name__contains=type.capitalize())
        print(supporters)
        if supporters.first() != None:
            data["type"] = type
            data[type] = []
            for supporter in supporters:
                data[type].append({
                    "img": supporter.img.url, 
                    "name": supporter.name, 
                    "type": supporter.type.name,
                    "sizeCategory": supporter.size.name,
                    "size": supporter.size.size
                })
            data["success"] = True
            
    return JsonResponse(data)

participants/views.py
from django.shortcuts import render
from django.http import JsonResponse
from participants import models
# Create your views here.
def parti(request):
    data = {}
    return render(request, "main-pages/parti.html", data)


def participants(request):
    data = {
        "success": False,
    }
    
    if request.method == "GET":
        participants = models.Participant.objects.all()
        if participants.first() != None:
            data["participants"] = []
            for participant in participants:
                data["participants"].append({
                    "name": participant.name, 
                    "photo": participant.photo.url, 
                    "comment": participant.comment})
            data["success"] = True

    return JsonResponse(data)

def agency(request):
    data = {
        "success": False,
    }
    if request.method == "GET":
        agency = models.Agency.objects.all()
        if agency.first() != None:
            data["agency"] = []
            for participant in agency:
                data["agency"].append({
                    "name": participant.name, 
                    "photo": participant.photo.url, 
                    "desc": participant.desc})
            data["success"] = True

    return JsonResponse(data)

about/templates/main-pages/about-dolc.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>DOLC 2019 - About - DOLC</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico" />
    <link rel="stylesheet" typ="text/css" href="{% static 'css/main-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/about-dolc-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/contact-style.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/about-dolc-script.js'%}"></script>
</head>
<body>
	<nav class="l-nav--main-page">
		{% include 'reusable-pages/navbar.html' %}
	</nav>
	<section class="l-page js-animation">
		<div class="l-front-section l-col--center js-front-section js-animation">
			<div class="c-front-section__logo l-image--default js-front-section__logo js-animation"></div>
		</div>
		<div class="l-profile-section l-col--center">
			<div class="l-profile-section__profile">
				<div class="js-profile-section__title js-animation">
					<h1 class="c-profile-section__title l-col--center">
						<div class="c-profile-section__line-art js-profile-section__line-art js-animation js-animation-delay--0"></div>
						DAYS OF LAW CAREER
					</h1>
				</div>
				<div class="l-profile-section__picture">
					<div class="c-circle-art--0 c-profile-section__circle-art--top js-circle-art--0 js-animation">
						<div class="c-circle--medium"></div>
						<div class="c-circle--medium"></div>
						<div class="c-circle--medium"></div>
						<div class="c-circle--medium"></div>
					</div>
					<div class="c-profile-section__image l-image--default js-profile-section__image js-animation"></div>
					<div class="c-profile-section__line-art--ver js-profile-section__line-art--ver js-animation"></div>
					<div class="c-profile-section__line-art--hor js-profile-section__line-art--hor js-animation"></div>
					<div class="c-circle-art--0 c-profile-section__circle-art--bottom js-circle-art--0 js-animation">
						<div class="c-circle--medium"></div>
						<div class="c-circle--medium"></div>
						<div class="c-circle--medium"></div>
						<div class="c-circle--medium"></div>
					</div>
				</div>
				<p class="c-profile-section__para js-profile-section__para js-animation">
					Days of Law Career (DOLC) is an annual event, organized by Departemen Pengembangan Karier Badan Eksekutif Mahasiswa Fakultas Hukum Universitas Indonesia, for both law students and alumni to obtain information regarding access to career in the legal sector and also to help with the correct selection of profession in accordance with their talents and expertise. This event will feature a job fair, scholarship fair, workshops, talkshows and other additional events. With the theme “Exceed the Expectation, Reshape the Reality”, DOLC 2019 hopes to expand the horizon of law students and alumni so that they can discover new potentials and find a career that is in accordance with that potential.
				</p>
			</div>
		</div>
		<div class="l-contact-section">
			{% include 'reusable-pages/contact.html' %}
		</div>
    </section>
</body>
</html>

about/templates/main-pages/about-team.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>DOLC 2019 - About - Team</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico" />
    <link rel="stylesheet" typ="text/css" href="{% static 'css/main-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/about-team-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/contact-style.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/about-team-script.js'%}"></script>
</head>
<body>
	<nav class="l-nav--main-page">
		{% include 'reusable-pages/navbar.html' %}
	</nav>
	<section class="l-page js-animation">
        <div class="l-front-section l-col--center js-front-section js-animation">
			<div class="c-front-section__logo l-image--default js-front-section__logo js-animation"></div>
		</div>
		<div class="l-team-section l-col--center">
			<div class="js-team-section__title js-animation">
				<h1 class="c-team-section__title">
					<div class="c-team-section__line-art js-team-section__line-art js-animation js-animation-delay--0"></div>
					THE TEAM
				</h1>
			</div>
			<div class="l-team-section__team l-col--center">
				<div class="c-circle-art--0 c-team-section__circle-art--top js-circle-art--0 js-animation">
					<div class="c-circle--medium"></div>
					<div class="c-circle--medium"></div>
					<div class="c-circle--medium"></div>
					<div class="c-circle--medium"></div>
				</div>
				<div class="c-team-section__image js-team-section__image js-animation"></div>
				<div class="c-circle-art--0 c-team-section__circle-art--bottom js-circle-art--0 js-animation">
					<div class="c-circle--medium"></div>
					<div class="c-circle--medium"></div>
					<div class="c-circle--medium"></div>
					<div class="c-circle--medium"></div>
				</div>
			</div>
		</div>
		<div class="l-contact-section">
			{% include 'reusable-pages/contact.html' %}
		</div>
    </section>
</body>
</html>

events/templates/main-pages/events.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>DOLC 2019 - Events</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico" />
    <link rel="stylesheet" typ="text/css" href="{% static 'css/main-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/events-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/contact-style.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/events-script.js'%}"></script>
</head>
<body>
	<nav class="l-nav--main-page">
		{% include 'reusable-pages/navbar.html' %}
	</nav>
	<div class="c-wall js-wall js-animation">
		<div class="c-date-place__icon l-image--default c-wall__close-icon"></div>
	</div>
	<div class="l-popup-section js-popup-section js-animation">
		<div class="l-popup-section__popup">
			<div class="l-popup-section__picture">
				<div class="c-popup-section__image l-image--default"></div>
			</div>
			<div class="l-popup-section__content">
				<!-- <div class="c-popup-content__blur-eft--top"></div>
				<div class="c-popup-content__blur-eft--bot"></div> -->
				<h2 class="c-popup-section__title"></h2>
				<div class="l-popup-section__detail">
					<p class="c-popup-section__para"></p>
					<div class="l-popup-section__date-place">
						<div class="l-date-place__place l-row--center">
							<div class="l-date-place__icon l-image--default c-place__place-icon"></div>
							<div class="c-place__content"></div>
						</div>
						<div class="l-date-place__date l-row--center">
							<div class="l-date-place__icon l-image--default c-date__date-icon"></div>
							<div class="c-date__content"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<section class="l-page js-animation">
		<div class="l-event-section l-col--center">
			<div class="js-event-section__title js-animation">
				<h1 class="c-event-section__title">
					<div class="c-event-section__line-art js-event-section__line-art js-animation js-animation-delay--0"></div>
					EVENTS
				</h1>
			</div>
			<div class="l-event-section__event l-col--center">
			</div>
		</div>
        <div class="l-contact-section">
			{% include 'reusable-pages/contact.html' %}
		</div>
    </section>
</body>
</html>

home/templates/main-pages/home.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>Days of Law Career 2019</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="google-site-verification" content="m6qScjJ33HFZT-ggs-qNnws56T2mI-2jxautyezVlyY" />
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico" />
    <link rel="stylesheet" typ="text/css" href="{% static 'css/main-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/home-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/contact-style.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/home-script.js'%}"></script>
</head>
<body>
	<nav class="l-nav--main-page">
		{% include 'reusable-pages/navbar.html' %}
	</nav>
	<section class="l-page js-animation">
        <div class="l-front-section l-col--center js-front-section js-animation">
			<div class="l-front-section__caption">
				<h1 class="c-front-section__title js-front-section__title js-animation">
						Days of<br/>
						Law<br/>
						Career
					</pre>
				</h1>
				<div class="c-front-section__line js-front-section__line js-animation">
				</div>
				<div class="c-front-section__date js-front-section__date js-animation">
					<h3 class="c-front-section__year">
						2019
					</h3>
					<div class="c-front-section__day">
						<h4>Pre-event</h2>
						<h5>
							11 - 14 Feb.
						</h5>
					</div>
					<div class="c-front-section__day">
						<h4>Main event</h2>
						<h5>
							18 - 22 Feb.
						</h5>
					</div>
				</div>
			</div>
		</div>
		<div class="l-about-section l-col--center">
			<div class="l-profile--0">
				<div class="l-profile__picture--0 js-profile__picture js-animation">
					<div class="c-about-section__counter">
						<h1 class="c-page__counter">
							01
						</h1>
					</div>
					<div class="l-profile__rectangle-art--0 js-profile__rectangle-art js-animation">
					</div>
					<div class="c-profile__image--0 c-about-section__image js-profile__image js-animation">
					</div>
				</div>
				<div class="l-profile__content--0 js-profile__content js-animation">
					<div class="l-profile__title">
						<div class="l-profile__circle-art--0 js-profile__circle-art js-animation">
							<div class="l-circle-art__hor">
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
							</div>
							<div class="l-circle-art__hor">
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
								<div class="c-circle--large"></div>
							</div>
						</div>
						<h2 class="c-profile__title">
							What is DOLC?
						</h2>
					</div>
					<p class="c-profile__para">
						Days of Law Career (DOLC) is an annual event, organized by Departemen Pengembangan Karier Badan Eksekutif Mahasiswa Fakultas Hukum Universitas Indonesia, for both law students and alumni to obtain information regarding access to career in the legal sector and also to help with the correct selection of profession in accordance with their talents and expertise. This event will feature a job fair...
					</p>
					<a class="c-read-more" href="{% url 'about:dolc' %}">
						<div class="c-read-more__circle-art">
							<div class="c-circle--medium js-animation"></div>
							<div class="c-circle--medium js-animation"></div>
							<div class="c-circle--medium js-animation"></div>
						</div>
						<div class="c-read-more__label js-animation">
							Read more
						</div>
					</a>
				</div>
			</div>
		</div>
		<div class="l-register-section js-register-section js-animation">
			<div class="l-register-section__left js-register-section__left js-animation">
				<div class="l-register-section__content">
					<h1 class="c-page__counter c-register-section__counter">
						02
					</h1>
					<h2 class="c-register-section__title js-register-section__title js-animation">
						HAVEN'T REGISTERED YET?
					</h2>
					<div class="l-register-section__para js-register-section__para js-animation">
						<p>
						</p>
						<!-- <div class="c-read-more">
							<div class="c-read-more__circle-art">
								<div class="c-circle--medium js-animation"></div>
								<div class="c-circle--medium js-animation"></div>
								<div class="c-circle--medium js-animation"></div>
							</div>
							<div class="c-read-more__label js-animation">
								Read more
							</div>
						</div> -->
					</div>
				</div>
			</div>
			<div class="l-register-section__right l-col--center js-register-section__right js-animation">
				<a class="c-register-section__register-button" href="{% url 'regis:regis' %}">
					<div class="c-register-button-art"></div>
					Register
				</a>
			</div>
		</div>
		<div class="l-testi-section l-col--center">
			<!-- <h1 class="c-page__counter js-page__counter js-animation">
				03
			</h1> -->
			<h1 class="c-testi-section__title js-testi-section__title js-animation">
				<div class="c-testi-section__line-art js-testi-section__line-art js-animation js-animation-delay--0"></div>
				PARTICIPANTS
			</h1>
			<div class="l-testi-section__testi">
			</div>
			<!-- <a class="c-read-more" href="{% url 'parti:parti' %}">
				<div class="c-read-more__circle-art">
					<div class="c-circle--medium js-animation"></div>
					<div class="c-circle--medium js-animation"></div>
					<div class="c-circle--medium js-animation"></div>
				</div>
				<div class="c-read-more__label js-animation">
					See more
				</div>
			</a> -->
		</div>
		<div class="l-spon-media-section l-col--center js-spon-media-section js-animation">
			<div class="l-spon-media-section__spon-media">
				<div class="l-spon-media-section__sponsor js-spon-media-section__sponsor js-animation">
					<h2>SPONSORS</h2>
					<div class="l-spon-media-section__sponsor__content l-row--center">
					</div>
				</div>
				<div class="l-spon-media-section__media js-spon-media-section__media js-animation">
					<h2>MEDIA PARTNERS</h2>
					<div class="l-spon-media-section__media__content l-row--center">
					</div>
				</div>
			</div>
		</div>
		<div class="l-contact-section">
			{% include 'reusable-pages/contact.html' %}
		</div>
    </section>
</body>
</html>

home/templates/reusable-pages/contact.html
<address class="l-contact-page">
    <div class="l-contact-page__contact l-row--center">
        <div class="l-contact-page__icons l-row--center">
            <a class="c-contact-page__line-icon" href="http://line.me/ti/p/@kfn8901p" target="_blank"></a>
            <a class="c-contact-page__inst-icon" href="https://www.instagram.com/dolcfhui/" target="_blank"></a>
        </div>
        <h4 class="c-contact-page__name l-row--center">
            dolcfhui
        </h4>
    </div>
</address>

home/templates/reusable-pages/navbar.html
<nav class="l-nav--nav-page">
    <div class="l-nav--top l-ver-center">
        <a class="l-nav--top__web-icon" href="{% url 'home:home' %}">
            <div class="c-web-icon">
            </div>
        </a>
        <div class="l-nav--top__nav-button l-row--center">
            <button class="c-nav-button" data-state="true">
                <div class="c-nav-button__line-art c-nav-button__line-art--0"></div>
                <div class="c-nav-button__line-art c-nav-button__line-art--1"></div>
                <div class="c-nav-button__line-art c-nav-button__line-art--2"></div>
            </button>
        </div>
    </div>
    <div class="l-nav--bottom l-row--center js-nav--bottom js-animation">
        <div class="l-nav l-row--center">
            <a class="c-nav__button l-col--center js-nav__button js-animation" href="{% url 'home:home' %}">
                <div class="c-nav__button__content">
                    <h4>
                        Home
                    </h4>
                    <div class="c-nav__button__line">
                    </div>
                </div>
            </a>
            <div class="c-nav__button l-col--center c-nav__button__about js-nav__button js-animation">
                <div class="c-nav__button__content">
                    <div>
                        <h4>
                            About
                        </h4>
                        <div class="c-nav__button__line"></div>
                    </div>
                    <a class="js-animation" id="c-nav__about-dolc-button" href="{% url 'about:dolc' %}">
                        DOLC
                    </a>
                    <a class="js-animation" id="c-nav__about-team-button" href="{% url 'about:team' %}">
                        Team
                    </a>
                </div>
            </div>
            <a class="c-nav__button l-col--center js-nav__button js-animation" href="{% url 'events:events' %}">
                <div class="c-nav__button__content">
                    <h4>
                        Events
                    </h4>
                    <div class="c-nav__button__line">
                    </div>
                </div>
            </a>
            <a class="c-nav__button l-col--center js-nav__button js-animation" href="{% url 'parti:parti' %}">
                <div class="c-nav__button__content">
                    <h4>
                        Participants
                    </h4>
                    <div class="c-nav__button__line">
                    </div>
                </div>
            </a>
            <a class="c-nav__button l-col--center js-nav__button js-animation" href="{% url 'regis:regis' %}">
                <div class="c-nav__button__content">
                    <h4>
                        Registration
                    </h4>
                    <div class="c-nav__button__line">
                    </div>
                </div>
            </a>
        </div>
    </div>
</nav>

participants/templates/main-pages/parti.html
{% load static %}

<!DOCTYPE HTML>
<html>
<head>
	<title>DOLC 2019 - Participants</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="shortcut icon" type="image/x-icon" href="/media/icons/favicon.ico" />
    <link rel="stylesheet" typ="text/css" href="{% static 'css/main-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/participants-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/navbar-style.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/contact-style.css' %}" />
	<script type="text/javascript" src="{% static 'js/jquery-3.3.1.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/navbar-script.js'%}"></script>
	<script type="text/javascript" src="{% static 'js/participants-script.js'%}"></script>
</head>
<body>
	<nav class="l-nav--main-page">
		{% include 'reusable-pages/navbar.html' %}
	</nav>
	<section class="l-page js-animation">
		<div class="l-participants-section l-col--center">
			<div class="js-participants-section__title js-animation">
				<h1 class="c-participants-section__title">
					<div class="c-participants-section__line-art js-participants-section__line-art js-animation js-animation-delay--0"></div>
					PARTICIPANTS
				</h1>
			</div>
			<div class="l-participants-section__participants-con l-image--default js-participants-section__participants-con js-animation">
				<button class="c-participants-section__slide-button c-participants-section__left-button l-image--default js-participants-section__slide-button js-animation"></button>
				<button class="c-participants-section__slide-button c-participants-section__right-button l-image--default js-participants-section__slide-button js-animation"></button>
				<div class="l-participants-section__participants l-row--center js-animation">
				</div>                                                           
				<div class="l-participants-section__decor">
					<div class="c-participants-section__chair-decor l-image--default"></div>
				</div>
			</div>
		</div>
        <div class="l-contact-section">
			{% include 'reusable-pages/contact.html' %}
		</div>
    </section>
</body>
</html>